---
title: "Discussion about Missing Data"
subtitle: "Understanding and Addressing Missing Data in Exploratory Data Analysis"
author: Jiwon Choi
thanks: "Code and data are available at: https://github.com/jwonc4602/Discussion-about-Missing-Data. Reviewed by Heyucheng Zhang, and updated the paper based on the feedback."
date: today
date-format: long
format: pdf
number-sections: true
toc: true
bibliography: references.bib
---

# Introduction

Missing data is a common challenge in data collection and analysis, posing significant obstacles to obtaining accurate insights and making informed decisions. This issue, widely recognized in exploratory data analysis (EDA), requires a thorough understanding of its types and the implementation of strategic measures to lessen its effects. @gelmanhillvehtari2020 categorize missing data into three main types: Missing Completely At Random (MCAR), Missing at Random (MAR), and Missing Not At Random (MNAR), each with distinct characteristics and implications for data analysis. This paper follows the contents of several chapters from "Telling Stories with Data"[@Alexander] and examines these categories, provides examples, and discusses various approaches for managing missing data, stressing the need for specific strategies to ensure the integrity and reliability of analytical results.

# Discussion

## Categories of Missing Data

1. **Missing Completely At Random (MCAR):** MCAR data lacks any association with observed or unobserved variables. A practical example of MCAR is a technical error causing loss of data from a subset of survey responses, such as the accidental deletion of responses from three randomly selected states in a national survey. This randomness does not bias the analysis, though proving data is MCAR can be difficult.

2. **Missing at Random (MAR):** MAR occurs when the likelihood of missing data is related to other observed data but not the missing data itself. For instance, in survey data, men might be less likely to answer questions about income. This can be modeled by removing income data for states with the highest male populations, illustrating the impact on income-related analyses.

3. **Missing Not At Random (MNAR):** MNAR data's absence is directly related to its own value or unobserved variables. An example involves higher-income individuals opting out of income questions due to privacy concerns. This introduces bias, as the missingness depends on the variable of interest itself.

## Strategies for Handling Missing Data

Handling missing data requires a thoughtful approach that considers the nature of the missingness and the specific context of the analysis. Sore example, software tools like the mice package in R facilitates various imputation techniques, allowing for more nuanced handling of missing data. The following strategies offer different ways to mitigate the impact of missing data:

- **Dropping Observations:** This straightforward approach involves removing data points with missing values. While simple, it can lead to the loss of valuable information, especially if the missingness is not MCAR.

- **Imputing Values:** Imputation involves replacing missing values with substitutes, such as the mean of the available data. This method can help retain data points but may introduce bias, particularly if the data is MNAR.

- **Multiple Imputation:** A more sophisticated technique, multiple imputation creates several imputed datasets and combines them to account for the uncertainty around the missing values. This approach is often more robust but requires careful implementation and interpretation.

## Ethical Considerations in Managing Missing Data
The ethical implications of handling missing data emphasizes the need for transparency and careful consideration of potential biases. It's crucial to acknowledge how different methods might influence the results and to strive for approaches that minimize harm, especially in sensitive research areas. Collaboration with subject-matter experts and adherence to ethical guidelines ensures the integrity of the analysis and respects the confidentiality and privacy of participants.

# Conclusion
Missing data is a complex issue that necessitates careful consideration and strategic handling in the context of EDA. Understanding the type of missingness—MCAR, MAR, or MNAR—is crucial for choosing an appropriate strategy to address it. Whether through data omission, imputation, or more advanced methods like multiple imputation, the chosen approach must be applied judiciously, with an awareness of its limitations and potential biases. Ultimately, the goal is to minimize the impact of missing data on the analysis, ensuring that the findings are as accurate and reliable as possible. Furthermore, acknowledging and documenting the handling of missing data is essential for transparency and reproducibility in research. As the field evolves, ongoing exploration of methods for managing missing data will remain a key aspect of ensuring the quality and integrity of data analysis.

\newpage


# References


